const OK = 200;
const CREATED_SUCCESS = 201;
const BAD_REQUEST_ERROR = 400;
const UNAUTHORIZEN_ERROR = 401;
const FORBIDDEN_ERROR = 403;
const NOT_FOUND_ERROR = 404;
const DUPLICATE_ERROR = 409;
const INTERNAL_ERROR = 500;

export default {
  OK,
  CREATED_SUCCESS,
  BAD_REQUEST_ERROR,
  UNAUTHORIZEN_ERROR,
  FORBIDDEN_ERROR,
  NOT_FOUND_ERROR,
  DUPLICATE_ERROR,
  INTERNAL_ERROR,
};
